### ISSUE TITLE
Strength/Heaviness Modifiers don't work properly.

### ISSUE THREAD

**Issue by anom3** [Patashu/Entwined-Time#1]
Currently, it seems that Strength and Heaviness Modifiers actually set the strength/heaviness to the actors _durability_ +/- 1 for some reason.

To Reproduce:
Go into the editor.
Place Heavy, and an Iron Crate, with ground below. Give Heavy a Strength Plus modifier.
Give Heavy enough moves to reach the crate.
Heavy can not push the crate, despite that an object with Gravity strength, such as Heavy with +1 Strength, should be able to push an Iron Crate, which has a Heaviness of Iron.

**Comment by Patashu** [comment]
Good spot thanks, will be fixed in the next build

**Comment by anom3** [comment]
... I think this issue can be closed.
