### ISSUE TITLE
Collecting magenta time crystal as green player and  seems to be bugged.

### ISSUE THREAD

**Issue by anom3** [Patashu/Entwined-Time#2]
Collecting a magenta time crystal as a player with green time colour causes an empty rewind slot to be locked. However, on unlocking this slot, the empty slot goes _above_ the pointer. In addition, the counter increases by 2.

Rewinding an empty slot seems to have no effect.

**Comment by Patashu** [comment]
I'm a little scared of the time crystal code, but this does seem like a fairly fundamental interaction that should work as expected, so I'll add it to my TODO list.
